# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-17 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cowhite_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_post_images'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='categories',
            field=models.ManyToManyField(blank=True, to='django_cowhite_blog.Category'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='related_posts',
            field=models.ManyToManyField(blank=True, to='django_cowhite_blog.BlogPost'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Optional. This title is inserted in HTML Title tag. If not filled, blog title will be used.', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='D', max_length=1),
        ),
    ]
